### ISSUE TITLE
App Batch Download Mode

### ISSUE THREAD

**Issue by ay-kay** [DiOS-Analysis/DiOS#1]
Looking for an additional mode, e.g. called "DownloadOnly", that allows for bulk app downloading and caching app packages in the DiOS backend database for further processing. This would allow to fill up the backend while connected to a high-speed Internet connection, while later analysis could be performed almost offline. 

In addition, looking for a configuration switch to keep a copy of the IPA files in the file system.

**Comment by artemk** [comment]
Did you have a chance to work on this?

**Comment by tuusberg** [comment]
Hi guys!

I'm planning to use Pilot to download apps from App Store, so i guess I'd have to implement it.
I want to make a PR when I finish, is it still an open issue?

**Comment by awein** [comment]
Closing this issue unfixed due to iOS 9 changes:
* the AppStore won't download fat binaries anymore (app may not be executable on other devices)
* archiving of apps is not possible anymore (at least not by using built in mechanisms)
