### ISSUE TITLE
Problem with AAExecutorDaemon

### ISSUE THREAD

**Issue by ReverseMan** [DiOS-Analysis/DiOS#11]
When i run an app on ios device,the AAExecutorDaemon will output the following logs:
"2015-12-11 00:01:24.872 aaexecutord[4954:99503] UIAutomation is not enabled on this device. UIAutomation must be enabled in Settings."

and then exit.

But this problem can't  be solved after i enable the "UIAutomation" setting using xcode.

So how to fix this issue? Thanks

**Comment by awein** [comment]
Which iOS version do you use?
Sounds like the UIAutomation version and the iOS version might not match...

**Comment by ReverseMan** [comment]
The ios version is 9.0.2.

Do you know how to fix this issue? Thanks.

**Comment by awein** [comment]
@ReverseMan DiOS is not yet compatible with iOS 9. I'll close this as a duplicate for #8. Please re-open if you have the same issues on iOS 8 as well.
