### ISSUE TITLE
Response code 423 from pilot

### ISSUE THREAD

**Issue by raymontag** [DiOS-Analysis/DiOS#4]
Hey,

we get very often the response 423 from the pilot. Due to this nearly all installation jobs fail. However installing by hand works and the pilot seems to fill the credentials. Suggestions?

**Comment by awein** [comment]
Device is on iOS 7 or 8?

**Comment by raymontag** [comment]
It's an iPad with iOS 7.1.2

**Comment by raymontag** [comment]
Ok, after some research today I found out how to reproduce the issue (at least with my setup):

* Some installation failed. Due to this the pilot responded with a 400, probably in this line https://github.com/DiOS-Analysis/Pilot/blob/master/SBServerTweak/SBServerTweak/SBSTHTTPServer.m#L164
* After this the internal state of the pilot is not updated as a request to it with /status says that a task is still running.
