### ISSUE TITLE
Cannot execute apps with DiOS

### ISSUE THREAD

**Issue by raymontag** [DiOS-Analysis/DiOS#5]
Hey,

I cannot execute apps with DiOS. I always get the following error:

    [WARNING/DeviceServer-1:1:1:1] Connection to device <MuxDevice: ID 1 ProdID 0x12a6 Serial 'f975bb8de21cd2a78841f19dfc4d6647d00653b4' Location 0x10002> died!
    ERROR:worker:Executing job failed: HTTPConnectionPool(host='127.0.0.1', port=40105): Max retries exceeded with url: /execute/com.google.chrome.ios (Caused by <class 'socket.error'>: [Errno 104] Connection reset by peer)

After that the device loop stops. Do you have suggestions? Pilot and AAExecutorDaemon is installed.

**Comment by awein** [comment]
**This is not a support forum**
Please take a look at the wiki on how to run DiOS (https://github.com/DiOS-Analysis/DiOS/wiki/Initial-Setup). I would assume your should read https://github.com/DiOS-Analysis/DiOS/wiki/Initial-Setup#building-the-dios-pilot again and restart SpringBoard afterwards.

**Comment by raymontag** [comment]
Sure it's not. However I followed exactly the instructions and it doesn't work. I just hoped that you or someone else experienced this issue, too. But OK, I will go alone with this one.
