### ISSUE TITLE
iOS 8.4 Compatibility

### ISSUE THREAD

**Issue by jeffball55** [DiOS-Analysis/DiOS#6]
I've been able to get DiOS to the point where it will startup, install the selected application,
and then attempts to begin driving the application, but it immediately crashes springboard.  I'm running on a jailbroken iOS 8.4 (12H143) iPad Air. When the crash happens syslog has the following entries:

> Aug  3 17:44:54 Bobs-iPad SpringBoard[1072] <Error>: -[SBUIController launchIcon:fromLocation:]: unrecognized selector sent to instance 0x100752a20
> Aug  3 17:44:54 Bobs-iPad SpringBoard[1072] <Error>: *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[SBUIController launchIcon:fromLocation:]: unrecognized selector sent to instance 0x100752a20'

As you mentioned, this is due to DiOS not yet supporting iOS 8.4.  Would it be possible to update DiOS to support iOS 8.4?

**Comment by tyyts1234** [comment]
I'm also working on DiOS now ,i got the backend and worker okay , but when  i installed the SBServerTweak and AAexecutor , i found the SBServer did not work on my pad. Even more ,i can not  make package for the Analyzer plugin ...Could u plz send me your DiOS file,especially the pilot file and the basicanalyzer . Thank u very much!

**Comment by awein** [comment]
@jeffball55 DiOS is currently not compatible with iOS 8.4 but I'm planning to fix this issue very soon

**Comment by tyyts1234** [comment]
I'm also working on DiOS now ,i got the backend and worker okay , but when i installed the SBServerTweak and AAexecutor , i found the SBServer did not work on my pad. Even more ,i can not make package for the Analyzer plugin ...Could u plz send me your DiOS file,especially the pilot file and the basicanalyzer . Thank u very much!
@jeffball55
@

**Comment by jeffball55** [comment]
As @awein has mentioned in previous [bugs](https://github.com/DiOS-Analysis/DiOS/issues/5), this is not a support forum.  I will note that following the instructions for DiOS [here](https://github.com/DiOS-Analysis/DiOS/wiki/Initial-Setup) and the [here](https://github.com/DiOS-Analysis/DiOS/wiki/Running-DiOS) worked with the small exception that I needed to modify the SBServerTweak's Makefile to set the SBServerTweak's ARCHS variable to include arm64 in order for the binaries to run on my iPad Air.

**Comment by tyyts1234** [comment]
@jeffball55  okay，but what did u do with the SBServerTweak's Makefile ? i really have no idea.

**Comment by tyyts1234** [comment]
i can finish installing both aaexecutor and sbservertweak ,but i can only see aaexecutor running by uesing top .Is the servertweak installed failed?

**Comment by raymontag** [comment]
@tyyts1234 the servertweak is a tweak for SpringBoard. That is, it hasn't it's own process but injects itself in SpringBoard. To check if it is running you can type into Safari: http://:8080/status and if you get a response it is working.

**Comment by tyyts1234** [comment]
@raymontag   i really get the information “message 404 not found ” what is the problem?

**Comment by raymontag** [comment]
@tyyts1234 than the tweak isn't installed correctly. Have you killed SpringBoard? If not restart the device.

**Comment by tyyts1234** [comment]
@raymontag  i've already restarted ,but sitll did not work . it drove me crazy!

**Comment by awein** [comment]
@tyyts1234 @raymontag: Please do not miss-use the issue tracker for discussions and switch to IRC: https://github.com/DiOS-Analysis/DiOS/wiki/Support

**Comment by awein** [comment]
Fixed with https://github.com/DiOS-Analysis/Pilot/commit/db073d326751be6b969ee5a5e055fc0e8b5385d4
