### ISSUE TITLE
Can not execute APPS with DiOS

### ISSUE THREAD

**Issue by tyyts1234** [DiOS-Analysis/DiOS#7]
i have successfully installed apps through DiOS,but when i click execute button ,errors came out .And my iPad went into the safe mode，the syslog : 
 
ERROR:worker:Executing job failed: ('Connection aborted.', BadStatusLine("''",))
ERROR:worker:traceback: Traceback (most recent call last):
  File "worker.py", line 61, in run
    job.execute()
  File "/Users/zhen/Desktop/DiOS/Worker/job.py", line 377, in execute
    self._execute_app(pilot, bundleId, runId, executionStrategy)
  File "/Users/zhen/Desktop/DiOS/Worker/job.py", line 321, in _execute_app
    pilot.run_auto_execution(bundleId, taskInfo=taskInfo)
  File "/Users/zhen/Desktop/DiOS/Worker/pilot.py", line 111, in run_auto_execution
    r = requests.post("%s/execute/%s" % (self.baseUrl, bundleId), data=json.dumps(data))
  File "/Library/Python/2.7/site-packages/requests/api.py", line 108, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine("''",))

ERROR:worker:Device loop will be stopped now.

my iPad was 8.1.
What's the problems??

**Comment by awein** [comment]
Please attach the device syslog and the crash report for SpringBoard as well. The worker output just tells us that SpringBoard crashed...

**Comment by awein** [comment]
Just recognized your iPad is on iOS 8.1 - the latest version of DiOS requires 8.4 and would crash otherwise. Please use an older version of the SpringBoard tweak which is compatible with 8.1.
https://github.com/DiOS-Analysis/Pilot/commit/74e7b9f155c954534fadf8b714bf1e44fccf5e5c should be fine

**Comment by tyyts1234** [comment]
Ok,i'll try it .

**Comment by awein** [comment]
@tyyts1234 issue resolved?

**Comment by tyyts1234** [comment]
i am a little busy recently ,but i 'll still  try it .if any results,i 'll  report it soon.

**Comment by tyyts1234** [comment]
Can it run in IOS 9.0 or the higher version?

**Comment by kunal-relan** [comment]
I am not able to make package the SBServertweak it says , architecture not supported

**Comment by awein** [comment]
@tyyts1234: iOS 9 is not yet supported - there is already an issue for that (https://github.com/DiOS-Analysis/DiOS/issues/8). Can this issue be closed then?
