### ISSUE TITLE
I am not able to build SBServertweak on iphone sdk 9.2

### ISSUE THREAD

**Issue by kunal-relan** [DiOS-Analysis/DiOS#9]
I am not able to build it on iphone sdk 9.2 and the error says unsupported architecture,kindly help

**Comment by awein** [comment]
The build works fine with the latest iOS SDK (9.1). Please make sure you've followed the instructions at https://github.com/DiOS-Analysis/DiOS/wiki/Initial-Setup and use the corresponding Pilot version that matches the iOS version of your device (https://github.com/DiOS-Analysis/Pilot/tags).
